// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbG5hsmNHxYore_1SE7sQrXSLaKVcPHS4',
    appId: '1:702644666760:web:f246fad4b86ed2062d7a3d',
    messagingSenderId: '702644666760',
    projectId: 'chat-app-dc792',
    authDomain: 'chat-app-dc792.firebaseapp.com',
    storageBucket: 'chat-app-dc792.appspot.com',
    measurementId: 'G-1WFW0H3H00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj6Gh0yEfsrBn7IcVW80Digfq5hT6ocIM',
    appId: '1:702644666760:android:30af6f4b1c0015702d7a3d',
    messagingSenderId: '702644666760',
    projectId: 'chat-app-dc792',
    storageBucket: 'chat-app-dc792.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7u-TVnqU1vV5VFjE1MfJrxqdYHZw1Ne4',
    appId: '1:702644666760:ios:b1c7a687e01dcc742d7a3d',
    messagingSenderId: '702644666760',
    projectId: 'chat-app-dc792',
    storageBucket: 'chat-app-dc792.appspot.com',
    iosClientId: '702644666760-0jv5jjcoamgtk3n1sg22f813getd2u52.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7u-TVnqU1vV5VFjE1MfJrxqdYHZw1Ne4',
    appId: '1:702644666760:ios:b1c7a687e01dcc742d7a3d',
    messagingSenderId: '702644666760',
    projectId: 'chat-app-dc792',
    storageBucket: 'chat-app-dc792.appspot.com',
    iosClientId: '702644666760-0jv5jjcoamgtk3n1sg22f813getd2u52.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
